In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('Dataset\BC250_2017_Terra_Indigena_A.csv')

In [3]:
dataset.head()

,FID,id_objeto,nome,nomeabrev,geometriaaproximada,perimetrooficial,areaoficialha,grupoetnico,datasituacaojuridica,situacaojuridica,nometi,id_produtor,id_elementoprodutor,codigofunai,geom
0,BC250_2017_Terra_Indigena_A.1,1,Pacheca,Pacheca,Não,28109800.0,185.21,Guarani,2001/1/15,Regularizada,Pacheca,250000,2.0,NaN,MULTIPOLYGON (((-51.817032999999896 -31.170511...
1,BC250_2017_Terra_Indigena_A.2,2,Cantagalo,Cantagalo,Não,885605.0,283.68,Guarani Mbyá,2007/1/11,Homologada ou demarcada,Cantagalo,250000,3.0,NaN,MULTIPOLYGON (((-51.0340119999999 -30.19090999...
2,BC250_2017_Terra_Indigena_A.3,3,Guarani de Águas Brancas,Guarani de Águas Brancas,Não,9000000.0,230.00,Guarani,1996/2/13,Declarada,Guarani de Águas Brancas,250000,4.0,NaN,"MULTIPOLYGON (((-51.60478499999989 -30.766948,..."
3,BC250_2017_Terra_Indigena_A.4,4,Capivari,Capivari,Não,3465950.0,43.32,Guarani Mbyá,2003/1/8,Regularizada,Capivari,250000,7.0,NaN,MULTIPOLYGON (((-50.359660999999896 -30.359487...
4,BC250_2017_Terra_Indigena_A.5,5,Salto Grande do Jacuí,Salto Grande do Jacuí,Não,7258320.0,234.96,Guarani,2002/11/20,Regularizada,Salto Grande do Jacuí,250000,1.0,NaN,MULTIPOLYGON (((-53.2281029999999 -29.07109199...

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FID                   432 non-null    object
 1   id_objeto             432 non-null    int64
 2   nome                  432 non-null    object
 3   nomeabrev             428 non-null    object
 4   geometriaaproximada   431 non-null    object
 5   perimetrooficial      203 non-null    float64
 6   areaoficialha         243 non-null    float64
 7   grupoetnico           280 non-null    object
 8   datasituacaojuridica  224 non-null    object
 9   situacaojuridica      431 non-null    object
 10  nometi                221 non-null    object
 11  id_produtor           432 non-null    int64
 12  id_elementoprodutor   424 non-null    float64
 13  codigofunai           0 non-null      float64
 14  geom                  432 non-null    object
dtypes: float64(4), int64(2), object(9)
memory usage: 50.8+ KB

In [5]:
dataset = dataset.drop(columns=["FID", "geom", "codigofunai"])

In [6]:
dataset.head()

,id_objeto,nome,nomeabrev,geometriaaproximada,perimetrooficial,areaoficialha,grupoetnico,datasituacaojuridica,situacaojuridica,nometi,id_produtor,id_elementoprodutor
0,1,Pacheca,Pacheca,Não,28109800.0,185.21,Guarani,2001/1/15,Regularizada,Pacheca,250000,2.0
1,2,Cantagalo,Cantagalo,Não,885605.0,283.68,Guarani Mbyá,2007/1/11,Homologada ou demarcada,Cantagalo,250000,3.0
2,3,Guarani de Águas Brancas,Guarani de Águas Brancas,Não,9000000.0,230.00,Guarani,1996/2/13,Declarada,Guarani de Águas Brancas,250000,4.0
3,4,Capivari,Capivari,Não,3465950.0,43.32,Guarani Mbyá,2003/1/8,Regularizada,Capivari,250000,7.0
4,5,Salto Grande do Jacuí,Salto Grande do Jacuí,Não,7258320.0,234.96,Guarani,2002/11/20,Regularizada,Salto Grande do Jacuí,250000,1.0